services:
  tabby-db:
    container_name: tabby-db
    build: .
    image: mysql/mysql-server:5.7.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'tabby-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
